import type { Metadata } from "next";

import "./globals.css";
//import Navbar from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "Call Center Module",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        
        {children}
      </body>
    </html>
  );
}
